apiVersion: v1
kind: Service
metadata:
  name: pgadmin-svc
  namespace: mosson
spec:
  type: ClusterIP
  selector:
    app: pgadmin
  ports:
    - name: pgadmin
      protocol: TCP
      port: 5050
      targetPort: 5050
