version: '2.2'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: es
    environment:
      - 'node.name=es'
      - 'cluster.name=es-docker-cluster'
      - 'bootstrap.memory_lock=true'
      - 'discovery.type=single-node'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 29200:9200
    networks:
      - elastic

  kib:
    image: docker.elastic.co/kibana/kibana:7.15.1
    container_name: kib
    ports:
      - 25601:5601
    environment:
      - 'ELASTICSEARCH_URL=http://es:9200'
      - 'ELASTICSEARCH_HOSTS=["http://es:9200"]'
    networks:
      - elastic
    depends_on: 
      - es
      
networks:
  elastic:
    driver: bridge