services:
  kib:
    image: kibana
    container_name: kib
    ports:
      - "5601:5601"
    environment:
      - 'ELASTICSEARCH_URL=http://es:9200'
      - 'ELASTICSEARCH_HOSTS=["http://es:9200"]'
      - 'ELASTICSEARCH_USERNAME=elastic'
      - 'ELASTICSEARCH_PASSWORD=secret123!'
    networks:
      - kibana
      - elastic
      
networks:
  kibana:
    name: kibana
    driver: bridge
  elastic:
    external: true