apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: activemq-rs
  namespace: mosson
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      name: activemq
      labels:
        app: activemq
      namespace: mosson
    spec:
      containers:
        - name: activemq
          image: 192.168.50.149:5000/activemq
          ports:
            - name: stomp
              protocol: TCP
              containerPort: 61616
            - name: amqp
              protocol: TCP
              containerPort: 5672
            - name: jolokia
              protocol: TCP
              containerPort: 8161

# Replacements
# my-replica-set -> app replica set name
# app-label -> app label name
# my-pod -> app pod name
# image-name -> app image name
# my-container -> app container name
# port -> app container port