apiVersion: v1
kind: Service
metadata:
  name: activemq-svc
  namespace: mosson
spec:
  type: ClusterIP
  selector:
    app: activemq
  ports:
    - name: stomp
      protocol: TCP
      port: 61616
      targetPort: 61616
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: jolokia
      protocol: TCP
      port: 8161
      targetPort: 8161
