apiVersion: v1
kind: Service
metadata:
  name: kibana-svc
  namespace: mosson
spec:
  type: ClusterIP
  selector:
    app: kibana
  ports:
    - name: kibana
      protocol: TCP
      port: 5601
      targetPort: 5601
