global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:

scrape_configs:
  - job_name: 'ccn-manager'
    metrics_path: '/q/metrics'
    scrape_interval: 15s
    static_configs:
    - targets: ['192.168.178.204:7100']
  - job_name: 'logging'
    metrics_path: 'q/metrics'
    scrape_interval: 15s
    static_configs:
    - targets: ['192.168.178.204:6003']
