version: "2.3"

services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
    - 1433:1433
    environment:
    - "ACCEPT_EULA=Y"
    - "SA_PASSWORD=password123!"
