services:
  db:
    image: mariadb
    networks: 
      - mariadb
    environment:
      MARIADB_ROOT_PASSWORD: secret123!
    ports:
      - 3306:3306

  adminer:
    image: adminer
    networks: 
      - mariadb
    ports:
      - 8080:8080

networks:
  mariadb:
    name: mariadb
    driver: bridge