services:
  postgres:
    image: postgres:18.2-alpine3.22
    container_name: postgres
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=secret123!'
    ports:
      - 5432:5432
    volumes:
      - pg18_data:/var/lib/postgresql/18/docker
    networks:
      - postgres
  pgadmin:
    image: elestio/pgadmin:REL-9_12
    container_name: pgadmin
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@admin.com'
      - 'PGADMIN_DEFAULT_PASSWORD=secret123!'
    ports:
      - 5050:80
    networks:
      - postgres

networks:
  postgres:
    name: postgres
    driver: bridge

volumes:
  pg18_data:
