apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-svc
  namespace: mosson
spec:
  type: ClusterIP
  selector:
    app: elasticsearch
  ports:
    - name: elastic
      protocol: TCP
      port: 9200
      targetPort: 9200
