services:
  artemis:
    image: artemis
    container_name: artemis
    ports:
    - "8161:8161"
    - "61616:61616"
    - "5672:5672"
    networks:
    - artemis

networks:
  artemis:
    name: artemis
    driver: bridge
  
